config/routes.rb
MFSocial::Application.routes.draw do

  namespace :account do 
    resources :photos
    resources :profiles
  end

  resources :likes do
    collection do
      post "destroy_like"
    end
  end

  resources :comments

  resources :posts

  namespace :account do 
    resources :albums
  end

  get "home/index"

  get "home/about_us"

  get "home/contact"

  root :to => 'home#index'

  devise_for :users

end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :comment_id, :post_id, :user_id

  belongs_to :user
  belongs_to :post
  belongs_to :comment

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  
  include LikesHelper
  # GET /likes
  # GET /likes.json
  def index
    @likes = Like.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @likes }
    end
  end

  # GET /likes/1
  # GET /likes/1.json
  def show
    @like = Like.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @like }
    end
  end

  # GET /likes/new
  # GET /likes/new.json
  def new
    @like = Like.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @like }
    end
  end

  # GET /likes/1/edit
  def edit
    @like = Like.find(params[:id])
  end

  # POST /likes
  # POST /likes.json
  def create
    @like = Like.new(params[:like])
    @like_type = []
    @like_type << params["like_type"]
    respond_to do |format|
      if @like.save
        if params["like_type"] == "comment"
          @likes = Like.find_all_by_comment_id(params[:like][:comment_id])
          @like_type << params[:like][:comment_id].to_s
        else
          @likes = Like.find_all_by_post_id(params[:like][:post_id])
          @like_type << params[:like][:post_id].to_s
        end
        
        #format.html { redirect_to @like, notice: 'Like was successfully created.' }
        format.js{@like_type}
        format.json { render json: @like, status: :created, location: @like }
      else
        format.html { render action: "new" }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /likes/1
  # PUT /likes/1.json
  def update
    @like = Like.find(params[:id])

    respond_to do |format|
      if @like.update_attributes(params[:like])
        format.html { redirect_to @like, notice: 'Like was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1
  # DELETE /likes/1.json
  def destroy_like
    @like_type = []
    @like_type << params["like_type"]
    
    if params["like_type"] == "comment"
      @like = Like.find_by_user_id_and_comment_id(params[:like][:user_id], params[:like][:comment_id])
      @like.destroy
      @like_type << params[:like][:comment_id].to_s
      @likes = Like.find_all_by_comment_id(params[:like][:comment_id])
    else
      @like = Like.find_by_post_id_and_user_id(params[:like][:post_id], params[:like][:user_id])
      @like.destroy
      @like_type << params[:like][:post_id].to_s
      @likes = Like.find_all_by_post_id(params[:like][:post_id])
    end

    respond_to do |format|
      #format.html { redirect_to likes_url }
      format.js{@like_type}
      format.json { head :no_content }
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper

    def current_user_like_check(post_id, id)

      @like = Like.find_by_post_id_and_user_id(:post_id => post_id.to_i, :user_id => id)
       Rails.logger.debug "================================================"
       Rails.logger.debug @like
       Rails.logger.debug "================================================"
      if @like.nil?
        return false
      else
        return true
    end
  end


end

app/views/likes/_form.html.erb
<%= form_for(@like) do |f| %>
  <% if @like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
      <% @like.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br />
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :comment_id %><br />
    <%= f.number_field :comment_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/likes/_users_like.html.erb
<% like_user_name = [] %>
<% likes.each do |like| %>
  <% if like.user_id == current_user.id %>
    <%  like_user_name.insert(0, "you") %>
  <% else %>
    <% like_user =  "#{like.user.first_name} #{like.user.last_name}" %>
    <%  like_user_name << like_user %>
  <% end %>
<% end  %>

<% if like_user_name.length > 0 %>
  <% case like_user_name.length %>
    <% when 1 %>
      <% if like_user_name[0] == "you" %>
        you like this.
      <% else %>
         <%= link_to like_user_name[0], root_url %> like this.
      <% end %>
     <% when 2 %>
      <% if like_user_name[0] == "you" %>
        you and <%= link_to like_user_name[1], root_url %>  like this.
      <% else %>
        <%= link_to like_user_name[0], root_url %> and <%= link_to like_user_name[1], root_url %> like this.
      <% end %>
     <% else %>
      <% if like_user_name[0] == "you" %>
        you, <%= link_to like_user_name[1], root_url %> and <%= link_to "#{like_user_name.length-2} others", root_url %>  like this.
      <% else %>
       <%= link_to like_user_name[0], root_url %>, <%= link_to like_user_name[1], root_url %> and <%= link_to "#{like_user_name.length-2} others", root_url %>  like this.
      <% end %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
<%  if @like_type[0] == "comment" %>
  $("#comment_like_<%=  @like_type[1] %>").html('');
  $("#comment_like_<%=  @like_type[1] %>").html('<%= escape_javascript( render :partial => "likes/users_like", :locals => {:likes => @likes} ) %>').fadeIn();

<%  else %>
  $("#post_like_<%=  @like_type[1] %>").html('');
  $("#post_like_<%=  @like_type[1] %>").html('<%= escape_javascript( render :partial => "likes/users_like", :locals => {:likes => @likes}  ) %>').fadeIn();
<%  end %>

app/views/likes/destroy_like.js.erb
<%  if @like_type[0] == "comment" %>
  $("#comment_like_<%=  @like_type[1] %>").html('');
  $("#comment_like_<%=  @like_type[1] %>").html('<%= escape_javascript( render :partial => "likes/users_like", :locals => {:likes => @likes} ) %>').fadeIn();

<%  else %>
  $("#post_like_<%=  @like_type[1] %>").html('');
  $("#post_like_<%=  @like_type[1] %>").html('<%= escape_javascript( render :partial => "likes/users_like", :locals => {:likes => @likes}  ) %>').fadeIn();
<%  end %>

app/views/likes/edit.html.erb
<h1>Editing like</h1>

<%= render 'form' %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<h1>Listing likes</h1>

<table>
  <tr>
    <th>Post</th>
    <th>Comment</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @likes.each do |like| %>
  <tr>
    <td><%= like.post_id %></td>
    <td><%= like.comment_id %></td>
    <td><%= like.user_id %></td>
    <td><%= link_to 'Show', like %></td>
    <td><%= link_to 'Edit', edit_like_path(like) %></td>
    <td><%= link_to 'Destroy', like, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<h1>New like</h1>

<%= render 'form' %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Post:</b>
  <%= @like.post_id %>
</p>

<p>
  <b>Comment:</b>
  <%= @like.comment_id %>
</p>

<p>
  <b>User:</b>
  <%= @like.user_id %>
</p>


<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>