config/routes.rb
MFSocial::Application.routes.draw do

  namespace :account do 
    resources :photos
    resources :profiles
  end

  resources :likes do
    collection do
      post "destroy_like"
    end
  end

  resources :comments

  resources :posts

  namespace :account do 
    resources :albums
  end

  get "home/index"

  get "home/about_us"

  get "home/contact"

  root :to => 'home#index'

  devise_for :users

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_js
  
  def index
    @posts = Post.all
    @post = Post.new
    @comment = Comment.new
    respond_to do |format|
      format.html {  render :layout => 'public_profile' }#index.html.erb
      format.json { render json: @posts}
      format.xml
    end
  end

  def about_us
  end

  def contact
  end

  private

  def load_js
    AssetManager.include_local_library [:application, :upload_image, :simple_common_functionality]
    AssetManager.include_contrib_library [:colorbox]
    AssetManager.include_css [
      :application,
    ]
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_comment_box.html.erb
<% @comments = @post.comments %>

<div class="comment-box-inner">
  <% unless @comments.nil? %>
  
  <div class="comment_post">

    <% @comments.each do |comment| %>
        <div id="comment_id_<%= comment.id %>" class="post_comment post_comment_child comment_child comment-content">
          <div class="image_name">
            <% if comment.user.profile_photo_id.blank? %>
              <%= link_to image_tag("profilePhoto/no-image.gif", :class => "profile_image", :id => "profile_image", :alt => "User's image", :size => "60x40"), root_url %>
            <% else %>
              <%= link_to image_tag(comment.user.profile_photo.avtar.url(:comment), :class => "profile_image", :id => "profile_image", :alt => "#{current_user.first_name} #{current_user.last_name}'s image"), root_url %>
            <% end %>
          </div>
          <div class="image_name">
            <div class="name_link_post comment_name_link">
              <div>
                <%= link_to "#{comment.user.first_name} #{comment.user.last_name} ", root_url %>
                
                <%= link_to "", comment, :method => "delete", :confirm => "Are you sure?", :id => "delete_link_#{comment.id}", :class => "close-button image-block inactive-delete-link", :remote => true %>
              </div>
              <div>
                <%= comment.content %>
              </div>
              <div>
                <span>
                  <% @status = comment.current_user_like? (current_user)  %>

                  <% if @status %>
                    <%= link_to "Like", likes_path("like_type" => "comment", :like => {:user_id => "#{current_user.id}", :post_id => "#{comment.post_id}", :comment_id => "#{comment.id}" }), :method => "post", :remote => true, :id => "like_comment_#{comment.id}", :class => "like_post_class disable_link" %>
                    <%= link_to "Unike", destroy_like_likes_path("like_type" => "comment", :like => {:user_id => "#{current_user.id}", :post_id => "#{comment.post_id}", :comment_id => "#{comment.id}" }), :method => "post", :remote => true, :id => "unlike_comment_#{comment.id}", :class => "unlike_post_class" %>
                  <% else %>
                    <%= link_to "Like", likes_path("like_type" => "comment", :like => {:user_id => "#{current_user.id}", :post_id => "#{comment.post_id}", :comment_id => "#{comment.id}" }), :method => "post", :remote => true, :id => "like_comment_#{comment.id}", :class => "like_post_class" %>
                    <%= link_to "Unike", destroy_like_likes_path("like_type" => "comment", :like => {:user_id => "#{current_user.id}", :post_id => "#{comment.post_id}", :comment_id => "#{comment.id}" }), :method => "post", :remote => true, :id => "unlike_comment_#{comment.id}", :class => "unlike_post_class disable_link" %>
                  <% end %>
                </span>
                
                <span><abbr class="timeago" title="<%= comment.timeago_format(comment.created_at) %>" style="border-style: none;"></abbr></span>
              </div>
              <div id="comment_like_<%= comment.id %>" class="post_like comment_like">
                <%= render "likes/users_like", :likes =>  comment.likes  unless comment.likes.length > 0 %>
              </div>
            </div>

          </div>

        </div>
    <% end %>
  </div>
  <% end %>
  <div class="comment-box-photo">
    <% if current_user.profile_photo_id.blank? %>
      <%= link_to image_tag("profilePhoto/no-image.gif", :class => "profile_image", :id => "profile_image", :alt => "User's image", :size => "35x35"), root_url %>
    <% else %>
      <%= link_to image_tag(current_user.profile_photo.avtar.url(:new_comment), :class => "profile_image", :id => "profile_image", :alt => "#{current_user.first_name} #{current_user.last_name}'s image"), root_url %>
    <% end %>
  </div>
  <div id="comment-box-form" class="comment-box-form" >
    <%= render :partial=>'comments/form', :locals => {:post_id => "#{@post.id}"} %>
  </div>
</div>
<div style="clear:both;"></div>

app/views/home/_post.html.erb
<div class="post_comment">
  <div class="post_comment_child">
    <div class="image_name">
      <% if post.user.profile_photo_id.blank? %>
        <%= link_to image_tag("profilePhoto/no-image.gif", :class => "profile_image", :id => "profile_image", :alt => "User's image", :size => "53x40"), root_url %>
      <% else %>
        <%= link_to image_tag(post.user.profile_photo.avtar.url(:comment), :class => "profile_image", :id => "profile_image", :alt => "#{current_user.first_name} #{current_user.last_name}'s image"), root_url %>
      <% end %>
    </div>
    <div class="image_name">
      <div class="name_link_post">
        <div>
          <%= link_to "#{post.user.first_name} #{post.user.last_name} ", root_url %> has updated his status.
        </div>
        <div>
          <%= post.content %>
        </div>
        <div>
          <span>
            <% @status = post.current_user_like? (current_user)  %>

            <% if @status %>
              <%= link_to "Like", likes_path(:like => {:user_id => "#{current_user.id}", :post_id => "#{post.id}" }), :method => "post", :remote => true, :id => "like_post_#{post.id}", :class => "like_post_class disable_link" %>
              <%= link_to "Unike", destroy_like_likes_path(:like => {:user_id => "#{current_user.id}", :post_id => "#{post.id}" }), :method => "post", :remote => true, :id => "unlike_post_#{post.id}", :class => "unlike_post_class" %>
            <% else %>
              <%= link_to "Like", likes_path(:like => {:user_id => "#{current_user.id}", :post_id => "#{post.id}" }), :method => "post", :remote => true, :id => "like_post_#{post.id}", :class => "like_post_class" %>
              <%= link_to "Unike", destroy_like_likes_path(:like => {:user_id => "#{current_user.id}", :post_id => "#{post.id}" }), :method => "post", :remote => true, :id => "unlike_post_#{post.id}", :class => "unlike_post_class disable_link" %>
            <% end %>
          </span>
          <span><%= link_to "Comment", "javascript:void(0);", :id => "comment_post_link_#{post.id}", :class => "comment_post_link" %></span>
          <span><%= link_to "Share", root_url, :remote => true %></span>
          <span><abbr class="timeago" title="<%= post.timeago_format %>" style="border-style: none;"></abbr></span>
        </div>
        <div id="comments_<%= post.id %>" class="comments">
          <div id="post_like_<%= post.id %>" class="post_like">
            <%= render "likes/users_like", :likes =>  post.likes %>
          </div>
          <% @post = post %>
          <%= render :partial => 'home/comment_box', :post => @post %>
        </div>
      </div>

    </div>
    
  </div>
  
</div>

app/views/home/_posts.html.erb
<div class="user-posts-wrapper" style="width: 100%;">
  <% @posts.each do |post| %>

    <%= render "home/post", :post => post %>

  <% end  %>
</div>

app/views/home/_status_space.html.erb
<div class="wrap">
  <div class="innerWrap">
    <%= form_for(@post, :remote => true) do |f| %>
    <%= f.hidden_field :by_user_id, :value => current_user.id %>
    <%= f.hidden_field :to_user_id, :value => current_user.id  %>
      <div class="field">
        <div class="message-box">
          <%= f.text_area :content, :class => "wall_post text_space", :rows => "1", :cols => "68", :placeholder => "what's on your mind?" %>
        </div>
        <div class="message-box-action">
          <%= f.submit  'Post' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/about_us.html.erb
<h1>Home#about_us</h1>
<p>Find me in app/views/home/about_us.html.erb</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/index.html.erb
<div id="mainContainer">
  <div id="leftColContainer">
    <div id="leftCol">
      <div id="pagelet_welcome_box">
        <div>
          <div class="image_name">
            <% if current_user.profile_photo_id.blank? %>
              <%= link_to image_tag("profilePhoto/no-image.gif", :class => "profile_image", :id => "profile_image", :alt => "User's image", :size => "60x40"), account_profile_path(current_user.profile) %>
            <% else %>
              <%= link_to image_tag(current_user.profile_photo.avtar.url(:profile), :class => "profile_image", :id => "profile_image", :alt => "#{current_user.first_name} #{current_user.last_name}'s image"), account_profile_path(current_user.profile) %>
            <% end %>
            <div  class="change_image_link" style="cursor: default;">
              <%= link_to "Change", new_account_photo_path, :id => "change_image_link" %>
            </div>
          </div>
          <div class="image_name">
            <div class="name_link">
              <%= link_to "#{current_user.first_name} #{current_user.last_name}", root_url %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="contentCol">
    <div id="rightCol">
      <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
    </div>
    <div id="update_icons">
      <span class="update-status"><%= link_to 'Update Status','javascript:void(0);' %></span>
    </div>
    <div id="contentArea">
      <div class="status-form-bar" style="border: 1px solid red;">
        <%= render "status_space" %>
      </div>
     
      <div id="status_div" style="width: 100%; border: 1px solid red; height: auto;">
       <%= render "posts" %>
      </div>
      
    </div>
  </div>
</div>